### ISSUE TITLE
FPS adjustment

### ISSUE THREAD

**Issue by moonjongsul** [ctu-mrs/bluefox3_ros#1]
How do I adjust FPS??

**Comment by matemat13** [comment]
Hmm let's see. As is, the driver will use the default framerate of the camera which should be the maximal frame rate, if I recall correctly. If you want to change it, it should be possible by writing the corresponding property using the `writeProperty()` method. You should be able to change the resolution, ROI, etc., according to what you need. If you only need a slower framerate, you can simply [throttle the topic using standard ROS tools](http://wiki.ros.org/topic_tools/throttle) and use the throttled topic. Hope this helps!
